# Generated by Django 5.0.7 on 2024-07-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='access_permission',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='added_by',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_cadre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_country_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_region',
        ),
    ]
