# Generated by Django 5.0.7 on 2024-07-31 07:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_email_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicdata',
            options={'verbose_name': 'Dynamic Data', 'verbose_name_plural': 'Dynamic Data'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='dynamicdata',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='dynamicdata',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='dynamicdata',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Dynamic Data'),
        ),
        migrations.AlterField(
            model_name='dynamicdata',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_data', to='myapp.userprofile', verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
    ]
